In [1]:
import numpy as np

In [2]:
myarr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], np.int64)

In [3]:
myarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int64)

In [4]:
myarr[2,3] #0,1,2 ....row

12

In [5]:
myarr[2,3] = 56

In [6]:
myarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 56]], dtype=int64)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr.shape #3 row and 4 column

(3, 4)

# There are 5 general mechanisms for creating arrays:

1. Array creation: Conversion from other Python structures

In [9]:
myarr.size

12

In [10]:
np.array({34,56,56})

array({56, 34}, dtype=object)

2. Intrinsic numpy array creation objects(e.g.,arrange,ones,zeros,etc.)

In [11]:
zeros = np.zeros((2,5))

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
zeros.shape

(2, 5)

In [14]:
zeros.dtype

dtype('float64')

In [15]:
rng = np.arange(15) #range

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace = np.linspace(1,5,12)
#linespace = np.linspace(1,50,10)

In [18]:
lspace
#linespace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

3. Random access

In [19]:
emp = np.empty((4,6)) #4 row and 6 column

In [20]:
emp

array([[1.12066673e-311, 7.70742408e-322, 0.00000000e+000,
        0.00000000e+000, 7.56587583e-307, 1.15998412e-028],
       [4.31603868e-080, 1.94919985e-153, 1.35717430e+131,
        8.48576822e-096, 9.58659700e+140, 6.01347002e-154],
       [6.03107000e-154, 6.03108138e-154, 6.01391519e-154,
        1.17633628e-095, 8.04868985e-096, 2.00007434e+174],
       [6.96752298e+252, 2.59050082e-144, 2.86530729e+161,
        2.59050167e-144, 4.82412328e+228, 1.04718130e-142]])

In [21]:
emp_like = np.empty_like(lspace)

In [22]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [23]:
ide = np.identity(45) #45x45 identity matrix

In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [25]:
ide.shape

(45, 45)

In [26]:
arr = np.arange(99)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

4. NUMPY AXIS

In [30]:
myarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 56]], dtype=int64)

In [31]:
myarr.sum(axis=0) #column sum

array([15, 18, 21, 68], dtype=int64)

In [32]:
myarr.sum(axis=1) #row sum

array([10, 26, 86], dtype=int64)

In [33]:
myarr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 56]], dtype=int64)

In [34]:
for item in myarr.flat:
    print(item)

1
2
3
4
5
6
7
8
9
10
11
56


In [35]:
myarr.ndim #number of dimensions

2

In [36]:
myarr.size

12

In [37]:
myarr.nbytes

96

5. New Concept

In [38]:
one = np.array([1,3,4,45,67])

In [39]:
one.argmax() #run as function #it gives index where max element is present

4

In [40]:
one.argmin()

0

In [41]:
one.argsort() #gives back index element value only

array([0, 1, 2, 3, 4], dtype=int64)

In [42]:
myarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 56]], dtype=int64)

In [43]:
myarr.argmax(axis = 0)

array([2, 2, 2, 2], dtype=int64)

6. Matrix operations

In [44]:
ar1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [45]:
ar2 = np.array([[14,22,31],
                [43,54,65],
                [75,86,98]])

In [46]:
ar1 + ar2

array([[ 15,  24,  34],
       [ 47,  59,  71],
       [ 82,  94, 107]])

In [47]:
ar1 * ar2

array([[ 14,  44,  93],
       [172, 270, 390],
       [525, 688, 882]])

In [48]:
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [49]:
ar1.sum()

45

In [50]:
ar1.max()

9

In [51]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
np.where(ar1>5) #1 st row and 2nd column

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [53]:
np.count_nonzero(ar1)

9

In [54]:
np.nonzero(ar1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))